### ISSUE TITLE
Does isle of SofaBoot support the circular dependency between sofa-modules | 是否支持 sofa-module 之间循环依赖

### ISSUE THREAD

**Issue by jnan806** [sofastack/sofa-boot#1028]
## In what area(s)?

> /area runtime

## Ask your question here

aplication dependents on both com.test.moduleA and com.test.moduleB, does isle of SofaBoot can work successfully if the ralations as following:
- sofa-module-A dependents on sofa-module-B,
- sofa-module-B also dependents on on sofa-module-A,

if circular dependency was support, I think it should be added in the Official website.

---

for example:

`sofa-module.properties` of sofa-module-A
``` properties
Module-Name=com.test.moduleA
Require-module=com.test.moduleB
```
`sofa-module.properties` of sofa-module-B
``` properties
Module-Name=com.test.moduleB
Require-module=com.test.moduleA
```

`pom.xml` of application
``` xml
<dependencies>

    <dependency>
        <groupId>com.test</groupId>
        <artifactId>moduleA</artifactId>
    </dependency>

    <dependency>
        <groupId>com.test</groupId>
        <artifactId>moduleB</artifactId>
    </dependency>

</dependencies>
```

**Comment by HzjNeverStop** [comment]
Not support
