### ISSUE TITLE
未来计划

### ISSUE THREAD

**Issue by leven-space** [sofastack/sofa-boot#1095]
## In what area(s)?

> /area operator

## Ask your question here
请问项目还会继续迭代更新吗？

**Comment by khotyn** [comment]
近期会发布 2023 的 RoadMap。最近在密集地开发 4.0.0 版本。

**Comment by leven-space** [comment]
cool

**Comment by HzjNeverStop** [comment]
SOFABoot 4.0.0 版本已经发布
