### ISSUE TITLE
sofaboot不支持polaris注册中心

### ISSUE THREAD

**Issue by MingJunDuan** [sofastack/sofa-boot#1180]
## In what area(s)?
Sofa-rpc5.8.4已经支持polaris，当前最新的sofaboot能否升级支持polaris

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

**Comment by HzjNeverStop** [comment]
欢迎提交一个PR来支持这一特性

**Comment by wangchengming666** [comment]
assign to me, ths

**Comment by wangchengming666** [comment]
related https://github.com/sofastack/sofa-boot/pull/1291
