### ISSUE TITLE
sofaboot-dependencies 3.x版本和springboot spirngcloud对应版本表能提供下吗

### ISSUE THREAD

**Issue by xiaoming728** [sofastack/sofa-boot#1200]

**Comment by HzjNeverStop** [comment]
SOFABoot 和 SpringBoot 的对应关系可以在文档里找到：https://www.sofastack.tech/projects/sofa-boot/overview/
SOFABoot 和 SpringCloud 无对应关系，你可以参考 SpringBoot 与 SpringCloud 的对应关系使用
