### ISSUE TITLE
skywalking兼容问题

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1202]
![image](https://github.com/sofastack/sofa-boot/assets/17228216/e66dc63e-6100-4b9b-8f96-60d0fdfc326d)
这里skywalking增强的interfaces.length不兼容?

**Comment by HzjNeverStop** [comment]
可以详细描述下你的问题，例如复现的场景

**Comment by HzjNeverStop** [comment]
> skywalking

这种情况建议通过 interfaceType 字段显示声明 interface

**Comment by yuanChina** [comment]
还是会报 has more than one interface
