### ISSUE TITLE
sofa jvm 服务与rpc 服务共存

### ISSUE THREAD

**Issue by siaron** [sofastack/sofa-boot#1208]
## In what area(s)?
runtime

## Ask your question here
- 场景
    - 多租户场景，一个基座应用包含多个扩展点。供租户扩展定制化业务
    - 租户扩展的代码与基座代码隔离（git仓库隔离），但是在运行时打成一个app（基座+扩展点）
- 问题
    - 在做租户扩展的时候无法在本地debug，我看sofa支持jvm服务和rpc服务。能做到一个api在本地debug的时候使用rpc（仅支持调试），但是合并到一起发布时用jvm服务调用（性能高）？

**Comment by HzjNeverStop** [comment]
如果同一个应用已经发布了 RPC 服务，应用内其他 Bean 调用这个服务默认是会优先使用 JVM 服务走内部调用
