### ISSUE TITLE
dynamic service invoke optimaze

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1209]
![image](https://github.com/sofastack/sofa-boot/assets/17228216/24c5b8f8-5eda-4572-8a94-a9a313eb0281)
这里应该怎么优化 缓存不生效

**Comment by HzjNeverStop** [comment]
麻烦详细描述下你的问题，最好能提供一个可复现的 demo

**Comment by yuanChina** [comment]
压测发现 大量的内存对象threadlocal 泄漏 定位源码怀疑
![image](https://github.com/sofastack/sofa-boot/assets/17228216/7bc5e39d-8179-45e6-ab47-2d07bfc2ef21)
有关 
![image](https://github.com/sofastack/sofa-boot/assets/17228216/eb610df0-d5c4-490d-9110-a6134267f6ca)
测试将set null 改为remove 重新测试 内存泄漏不复现 目前没有继续排查

**Comment by HzjNeverStop** [comment]
嗯这里确实应该remove掉 threadlocal 引用，SOFABoot会在下一个版本修复掉这个问题，感谢你的反馈
