### ISSUE TITLE
web-biz插件更新问题

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1226]
![image](https://github.com/sofastack/sofa-boot/assets/17228216/4bf2ee46-4410-4c77-bdbc-b5d2e313563c)
如图 每次更新插件都会报路径重复 这个是使用姿势不对么

**Comment by HzjNeverStop** [comment]
这个问题属于 sofaark 的问题，请提到 https://github.com/sofastack/sofa-ark
