### ISSUE TITLE
性能优化

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1232]
![image](https://github.com/sofastack/sofa-boot/assets/17228216/1c5e5ceb-b502-4e99-808a-bdb16497a414)
![image](https://github.com/sofastack/sofa-boot/assets/17228216/dc8293a1-23a2-465e-bdc7-f04194577afc)

一个方法里调用了4次sofaboot接口(JVM) 主要瓶颈就是这里的反射获取路径名,有什么优化建议么

**Comment by HzjNeverStop** [comment]
这里确实可以优化下，interfaceType 在初始化的时候就固定了，可以只获取一次 CanonicalName

将在下一个版本优化这个

**Comment by HzjNeverStop** [comment]
#1233
