### ISSUE TITLE
Setting custom thread pools through SofaService annotation does not take effect when interfaceType is not set

### ISSUE THREAD

**Issue by EvenLjj** [sofastack/sofa-boot#1245]
## Background
When setting a custom thread pool through SofaService annotations, the custom thread pool does not take effect when the interfaceType is not set.
![image](https://github.com/sofastack/sofa-boot/assets/15122299/46078d21-722a-49d3-b53d-8d0889c45d41)

**Comment by HzjNeverStop** [comment]
https://github.com/sofastack/sofa-boot/pull/1247
