### ISSUE TITLE
SOFABoot Integration testing

### ISSUE THREAD

**Issue by guanchao-yang** [sofastack/sofa-boot#126]
### Question

In SOFABoot, we should provide one integration testing cases.In this integration testing module, SOFABoot can mainly test the starters managed dependency by SOFABoot. 

### Your advice

Provide one SOFABoot integration testing project for testing all starters, avoid version conflict and dependency runtime error.In this  integration testing project, we should always run successfully before release SOFABoot.

**Comment by alaneuler** [comment]
This needs another project (or more).
