### ISSUE TITLE
SofaBoot:4.2.0 服务不能正常注册到 Nacos 中

### ISSUE THREAD

**Issue by zqiheng** [sofastack/sofa-boot#1283]
本地测试项目可以正常启动，日志显示 Service 已经注册完成。
![image](https://github.com/sofastack/sofa-boot/assets/34306759/85da024b-36ea-4f9d-a3b2-c56014214391)

但是在 Nacos 页面上不能看见注册的 Service。
<img width="1155" alt="image" src="https://github.com/sofastack/sofa-boot/assets/34306759/4230f8d5-ef57-4b2e-a241-a730adcedaac">

然后使用 Consumer 调用服务也的确报错。
![image](https://github.com/sofastack/sofa-boot/assets/34306759/cd801e93-1c89-417a-a634-886f8a917189)

不知道是我的配置问题还是环境或者版本问题，麻烦帮我看一下，谢谢！[示例代码](https://github.com/zqiheng/sofa-rpc-demo)

使用的组件版本：
- JDK 17
- Maven 3.9.2
- Nacos 2.0.3
- SofaBoot 4.2.0

**Comment by HzjNeverStop** [comment]
@zqiheng 在 SOFABoot 应用中，RPC 服务的注册通常是在应用的健康检查阶段完成后才执行的，从你的 demo 里看到你并未引入健康检查相关功能，因此 RPC 服务没有自动发布。

你有两个解决方案：
1. 引入 SOFABoot 的健康检查依赖，这样你的 RPC 服务会在健康检查通过后自动发布
```xml
        <dependency>
            <groupId>com.alipay.sofa</groupId>
            <artifactId>actuator-sofa-boot-starter</artifactId>
        </dependency>
```

2. 不引入 SOFABoot 的健康检查依赖，通过配置开启 RPC 服务的自动发布：
```properties
sofa.boot.rpc.enableAutoPublish=true

```

**Comment by zqiheng** [comment]
非常感谢，按照上述两种方案分别测试后，都可以注册成功！
