### ISSUE TITLE
sofa性能是否会再次优化

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1286]
![image](https://github.com/sofastack/sofa-boot/assets/17228216/5d61daa1-0992-4c70-abe9-bc17434baec1)

**Comment by HzjNeverStop** [comment]
从上述火焰图看，大部分性能消耗用于com.alipay.sofa.boot.ark.invoke.DynamicJvmServiceProxyFinder#findServiceComponent(java.lang.ClassLoader, com.alipay.sofa.runtime.spi.binding.Contract) 方法

你可以添加 sofa.boot.ark.jvmServiceCache=true 开启 Jvm 服务查找的缓存能力以降低这块逻辑的性能损耗
