### ISSUE TITLE
sofa.boot.ark.jvmServiceCache

### ISSUE THREAD

**Issue by yuanChina** [sofastack/sofa-boot#1296]
sofa.boot.ark.jvmServiceCache=true测试起来不生效,请问这个主要作用是什么,是会提高路由的性能么

**Comment by HzjNeverStop** [comment]
这个功能作用于 Ark Serverless 跨模块寻找 JVM 服务的场景。

开启这个配置后，对 JVM 服务的路由不是每次调用完整执行路由逻辑，而是先尝试查询缓存，从而提高路由的性能。

在 master 分支（4.2.0版本）中，您可以在 com.alipay.sofa.boot.ark.invoke.DynamicJvmServiceProxyFinder#findServiceComponent(java.lang.ClassLoader, com.alipay.sofa.runtime.spi.binding.Contract) 类中看到它生效的逻辑
