### ISSUE TITLE
BeanDefinitionUtil isFromConfigurationSource方法判断是不是有问题

### ISSUE THREAD

**Issue by wangya1529** [sofastack/sofa-boot#1330]
`   public static boolean isFromConfigurationSource(BeanDefinition beanDefinition) {
        return beanDefinition
            .getClass()
            .getCanonicalName()
            .startsWith(
                "org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader");
    }`

org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader 是否是org.springframework.context.annotation.ConfigurationClassBeanDefinition

**Comment by HzjNeverStop** [comment]
> ` public static boolean isFromConfigurationSource(BeanDefinition beanDefinition) { return beanDefinition .getClass() .getCanonicalName() .startsWith( "org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader"); }`
> 
> org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader 是否是org.springframework.context.annotation.ConfigurationClassBeanDefinition

通过 @Bean 注解创建的 BeanDefinition，getCanonicalName() 返回的是 org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.ConfigurationClassBeanDefinition
