### ISSUE TITLE
4.3.0版本无法在maven-snapshot获取

### ISSUE THREAD

**Issue by myprogo** [sofastack/sofa-boot#1333]
从https://oss.sonatype.org/content/repositories/snapshots里无法获取4.3.0版本构建包，请提供一下最新的资源仓库地址。

**Comment by HzjNeverStop** [comment]
https://mvnrepository.com/artifact/com.alipay.sofa/sofaboot-dependencies/4.3.0

您可以从中央仓库的 releease 仓库里获取
