### ISSUE TITLE
宿主应用和子应用日志隔离怎么解决？

### ISSUE THREAD

**Issue by superLovezhang** [sofastack/sofa-boot#1339]
## Ask your question here
我这里有一个宿主boot应用，用于加载其他三方biz子应用，宿主应用配置了logback日志xml，现在想要三方子应用都能配置自己日志的格式，日志存储地址该怎么解决？我看过sofa-common-tools项目，发现并不能解决我这个问题，恳请大佬解惑。

**Comment by HzjNeverStop** [comment]
这个问题可以咨询 https://github.com/koupleless/koupleless
