### ISSUE TITLE
关于项目开发的问题请教g

### ISSUE THREAD

**Issue by iyayu** [sofastack/sofa-boot#258]
@QilongZhang 
请原谅我的无知, 但是我实在是想不出去来在项目中使用模块隔离和类隔离来实现动态加载新模块(某个新功能)或动态更新模块.

这要怎么设计项目来更好, 麻烦您能给我点提示吗？

**Comment by QilongZhang** [comment]
@iyayu 没法给你具体提示，建议你把 SOFABoot 和 SOFAArk 文档和代码sample熟悉了解下。http://www.sofastack.tech/sofa-boot/docs/Home

**Comment by iyayu** [comment]
@QilongZhang  好的
