### ISSUE TITLE
原有的系统业务分层，怎么转入SOFABoot里

### ISSUE THREAD

**Issue by myprogo** [sofastack/sofa-boot#409]
<img width="362" alt="企业微信截图_15575646828763" src="https://user-images.githubusercontent.com/25293740/57567600-65ee7000-740e-11e9-9756-28b735a47e03.png">

像上图原有的系统业务分层，怎么转入SOFABoot里？怎么做模块化？类隔离打包的文件能否打包成一个模块文件，而不是按业务分层的文件。

**Comment by QilongZhang** [comment]
可以先参考 [SOFABoot 文档](https://www.sofastack.tech/sofa-boot/docs/QuickStart)  ， 类隔离的打包不用和业务分层一一对应，可以先了解这些功能怎么用。
