### ISSUE TITLE
JVM服务在父容器和模块中都可以使用的原理是?

### ISSUE THREAD

**Issue by TomorJM** [sofastack/sofa-boot#411]
如题

**Comment by TomorJM** [comment]
在SOFA源码里看到父容器和Module容器在初始化过程中都会调用到SofaRuntimeSpringContextInitializer.initApplicationContext方法, 父容器和模块容器共享一个SofaRuntimeContext的对象, 里面有个ComponentManager对象, 里面存放着定义service和reference的服务信息
照这样看的话是否是两个父子上下文共享一个bean对象实现的?

**Comment by QilongZhang** [comment]
> 在SOFA源码里看到父容器和Module容器在初始化过程中都会调用到SofaRuntimeSpringContextInitializer.initApplicationContext方法, 父容器和模块容器共享一个SofaRuntimeContext的对象, 里面有个ComponentManager对象, 里面存放着定义service和reference的服务信息
> 照这样看的话是否是两个父子上下文共享一个bean对象实现的?

嗯，是的。 Srpring  上下文隔离，对象是共享的。

**Comment by TomorJM** [comment]
问个问题:
1. 我看SOFAModule是在父容器发出ContextRefreshedEvent事件后开始执行子容器的初始化的
SofaModuleBeanFactoryPostProcessor里面将父容器里的BeanFactoryPostProcessor和BeanPostProcessor的BeanDefinition都取出来放在了**子容器**DynamicSpringContextLoader执行的时候将同样的BeanDefinition都注册到子容器里, 这一步的目的是什么?
2. 按照现在的父子容器加载顺序(子容器是在父容器refreshed完成后加载), 如果我在子容器里面需要将某个Bean(这里就叫它A)注册到父容器里, 也就是在父容器也可以直接拿到A并且使用A提供的服务, 这个注册时机放在哪里比较合适?

**Comment by QilongZhang** [comment]
问题一：将父上下文的 BeanPostProcessor  复制一份到子上下文，目的就是为了让这些 BeanPostProcessor 生效。

问题二：父上下文无法自动注入子上下文的 Bean，不过可以在子上下文中将 Bean 发布成 JVM 服务，父上下文中可以引用这个 JVM 服务；不过这里面有一个限制，因为父上下文优于自上下文刷新，如果在刷新父上下文过程中需要使用这个 JVM 服务，那么是不行的。

**Comment by TomorJM** [comment]
> 问题一：将父上下文的 BeanPostProcessor 复制一份到子上下文，目的就是为了让这些 BeanPostProcessor 生效。
> 
> 问题二：父上下文无法自动注入子上下文的 Bean，不过可以在子上下文中将 Bean 发布成 JVM 服务，父上下文中可以引用这个 JVM 服务；不过这里面有一个限制，因为父上下文优于自上下文刷新，如果在刷新父上下文过程中需要使用这个 JVM 服务，那么是不行的。

针对问题二: 现在貌似不能用JVM服务来解决这个问题, 因为问题描述中的A其实是一个HttpRequestHandler的实现, 因为现在HttpRequestHandler位于模块内, 而子容器是没有servlet的, 所以我的想法是将A在父容器再注册一次(在子容器内用自定义BeanFactoryPostProcessor), 让其有servlet的能力, 但是现在尴尬的是子容器在刷新的时候父容器已经刷新完成了, 这时候再往父容器registBeanDef的时候明显是不合理的, 不知道您能否指点一二?
PS:虽然这和Sofa模块不能有Controller能力的主旨相背=.=

**Comment by QilongZhang** [comment]
> > 问题一：将父上下文的 BeanPostProcessor 复制一份到子上下文，目的就是为了让这些 BeanPostProcessor 生效。
> > 问题二：父上下文无法自动注入子上下文的 Bean，不过可以在子上下文中将 Bean 发布成 JVM 服务，父上下文中可以引用这个 JVM 服务；不过这里面有一个限制，因为父上下文优于自上下文刷新，如果在刷新父上下文过程中需要使用这个 JVM 服务，那么是不行的。
> 
> 针对问题二: 现在貌似不能用JVM服务来解决这个问题, 因为问题描述中的A其实是一个HttpRequestHandler的实现, 因为现在HttpRequestHandler位于模块内, 而子容器是没有servlet的, 所以我的想法是将A在父容器再注册一次(在子容器内用自定义BeanFactoryPostProcessor), 让其有servlet的能力, 但是现在尴尬的是子容器在刷新的时候父容器已经刷新完成了, 这时候再往父容器registBeanDef的时候明显是不合理的, 不知道您能否指点一二?
> PS:虽然这和Sofa模块不能有Controller能力的主旨相背=.=

sorry，才看到你的回复。 子模块中含有 MVC 的扩展或者相关 Bean 确实无法作用到父上下文中。如果为了让子模块中定义的 HttpRequestHandler 生效，可以在子模块中声明一个 AutoConfiguration，将自定义的 RequestHandler发不成一个 Bean，这样的话，它的生命周期就是跟着父上下文了。
