### ISSUE TITLE
动态加载模块报错

### ISSUE THREAD

**Issue by grindwheel** [sofastack/sofa-boot#415]
![image](https://user-images.githubusercontent.com/10232714/58006525-dab26000-7b1a-11e9-874f-d01b6258555b.png)

**Comment by grindwheel** [comment]
设置spring boot 为非web应用

@SpringBootApplication
public class WebApplication {
    public static void main(String[] args) {
        SpringApplication springApplication = new SpringApplication(WebApplication.class);
        springApplication.setWebEnvironment(false);
        springApplication.run(args);
        System.getProperties().remove("spring.liveBeansView.mbeanDomain");
    }
}

**Comment by QilongZhang** [comment]
在宿主应用尝试引入如下依赖：
```xml
<dependency>
        <groupId>com.alipay.sofa</groupId>
       <artifactId>web-ark-plugin</artifactId>
</dependency>
```

**Comment by QilongZhang** [comment]
长时间没有收到反馈，issue 先关了，有需要麻烦重开。
