### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by shenkaiyang** [sofastack/sofa-boot#420]
您好，这边是北京新橙科技有限公司，为律师提供律所管理、法律大数据和专业服务为一体的智能办案系统，目前是法律行业独角兽企业，公司里也有几百名工程师，为了提升员工技能，这边想和您合作邀请您来公司做系列课程分享讲座。

**Comment by QilongZhang** [comment]
SOFAStack 暂无类似的课程分享，目前会不定期的开展 [SOFAStack 技术直播分享](https://www.sofastack.tech/activities?tag=%E7%9B%B4%E6%92%AD)，欢迎关注。其他形式的分享可以先邮件详细的沟通。
