### ISSUE TITLE
Sofa developer And sofa MVC

### ISSUE THREAD

**Issue by Darian1996** [sofastack/sofa-boot#423]
sofa 个人使用者，使用有限制吗？
还有 sofa MVC 对 Spring 的 GetMaping 支持吗？这个框架为什么不支持呢？
spring 的模式注解不通用吗？

**Comment by QilongZhang** [comment]
SOFAStack 开源对个人使用没有限制。 SOFA MVC 框架没有开源

**Comment by QilongZhang** [comment]
issue 先关闭，如果有其他问题，可以重开或者新建。
