### ISSUE TITLE
加载类时报previously initated loading for different type with name "xxxxxx"

### ISSUE THREAD

**Issue by grindwheel** [sofastack/sofa-boot#426]
看了下，这个实体类继承了某个类
![image](https://user-images.githubusercontent.com/10232714/58791440-ca26dd00-8624-11e9-8c11-1aa69a99b496.png)

**Comment by grindwheel** [comment]
两个是继承关系的类如果都用@SofaService注解，就会出现以上问题

**Comment by grindwheel** [comment]
@QilongZhang

**Comment by QilongZhang** [comment]
麻烦请提供下问题复现 demo。

**Comment by QilongZhang** [comment]
同 #428
