### ISSUE TITLE
类有plugin导出的，通过非序列化jvm调用，依然报这个错误Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class

### ISSUE THREAD

**Issue by grindwheel** [sofastack/sofa-boot#428]
![image](https://user-images.githubusercontent.com/10232714/59010354-840b8c80-8863-11e9-8972-3789f3bf27be.png)

**Comment by grindwheel** [comment]
另外如果通过序列化调用的方式，就会出现hessan序列化问题，调用接口返回对象是pb格式的，初步应该是pb格式的对象不能通过jvm序列化调用方式？ @QilongZhang

**Comment by QilongZhang** [comment]
@grindwheel 麻烦提供复现 demo，包括其他几个 issue 。

**Comment by QilongZhang** [comment]
这个 issue 很久了，我暂时关了。
