### ISSUE TITLE
sofaboot maven构建插件sofaboot-web-archetype 无法下载,账号也无法注册?

### ISSUE THREAD

**Issue by h812755591** [sofastack/sofa-boot#436]
Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.1.0:generate (default-cli) on project standalone-pom: The desired archetype does not exist (com.alipay.sofa:sofaboot-web-archetype:1.0-SNAPSHOT) -> [Help 1]
然后无法申请maven 私服账号跟密码?

**Comment by QilongZhang** [comment]
请问你是参考的商业版的文档吗？

**Comment by h812755591** [comment]
https://tech.antfin.com/docs/2/48619  这个链接的参考文档




------------------ 原始邮件 ------------------
发件人: "QilongZhang"<notifications@github.com>; 
发送时间: 2019年6月14日(星期五) 下午3:35
收件人: "sofastack/sofa-boot"<sofa-boot@noreply.github.com>; 
抄送: "西番"<812755591@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [sofastack/sofa-boot] sofaboot maven构建插件sofaboot-web-archetype 无法下载,账号也无法注册? (#436)




请问你是参考的商业版的文档吗？

**Comment by QilongZhang** [comment]
@h812755591  你参考的是商业版问题，开源版文档在 https://www.sofastack.tech/sofa-boot/docs/Home

**Comment by h812755591** [comment]
好的，明白，谢谢啦



------------------ 原始邮件 ------------------
发件人: "QilongZhang"<notifications@github.com>; 
发送时间: 2019年6月17日(星期一) 下午5:24
收件人: "sofastack/sofa-boot"<sofa-boot@noreply.github.com>; 
抄送: "西番"<812755591@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [sofastack/sofa-boot] sofaboot maven构建插件sofaboot-web-archetype 无法下载,账号也无法注册? (#436)




@h812755591  你参考的是商业版问题，开源版文档在 https://www.sofastack.tech/sofa-boot/docs/Home
