### ISSUE TITLE
3.0.0 版本不能再 SofaReference 中使用占位符 ${xxx} 注入属性

### ISSUE THREAD

**Issue by OrezzerO** [sofastack/sofa-boot#437]
```
@SofaReference(interfaceType = PortalApi.class, binding = @SofaReferenceBinding(bindingType = "rest", directUrl = "${application.apollo.portal.url}"))
    private PortalApi portalApi;
```
这种写法报错,不能识别注入的属性. 在之前的版本中,可以通过`ReferenceAnnotationBeanPostProcessor`注入 PlaceHolderBinder 来处理占位符,3.0.0 版本之后,使用`ServiceAnnotationBeanPostProcessor`就不行了. 有其他解决方案可以让我注入属性吗?

**Comment by QilongZhang** [comment]
3.1.0(3.x) 和 2.5.2(2.x) 两个版本开始支持注解中的替换符。

**Comment by OrezzerO** [comment]
了解了 👍
