### ISSUE TITLE
使用sofaboot开发短信服务无法注册成功

### ISSUE THREAD

**Issue by qinliang373** [sofastack/sofa-boot#439]
使用sofaboot 3.1.5开发短信服务，向nacos上无法注册成功，退回到3.1.3可以注册成功。
使用sofaboot3.1.5并不是所有服务都无法向nacos注册成功，经测试只有短信服务无法注册成功。
sofaboot 3.1.5
windows10
idea
jdk1.8
nacos1.0

**Comment by QilongZhang** [comment]
问题信息太笼统，能否提供具体的demo 复现问题？

**Comment by qinliang373** [comment]
@QilongZhang demo怎么发给你?

**Comment by QilongZhang** [comment]
> @QilongZhang demo怎么发给你?

直接上传至 github 即可.
