### ISSUE TITLE
sofa-boot支持sofa-bolt 1.5.x版本

### ISSUE THREAD

**Issue by dbl-x** [sofastack/sofa-boot#440]
sofa-bolt 1.4.x和1.5.x之间存在不兼容的问题，目前部分sofa-boot用户需要使用部分依赖了1.5.x的组件，需要sofa-bolt提供支持1.5.x的版本

**Comment by QilongZhang** [comment]
@leizhiyuan   一起关注一下， @dbl-x  升级sofa-bolt 版本放在 sofaboot 2.x 还是 3.x， 对 rpc 版本是否有要求？ -

**Comment by leizhiyuan** [comment]
有的，sofabolt 有不兼容的变更点。rpc 5.6.1中升级吧。放在3.x中。

**Comment by QilongZhang** [comment]
> 有的，sofabolt 有不兼容的变更点。rpc 5.6.1中升级吧。放在3.x中。

ok

**Comment by dbl-x** [comment]
@QilongZhang 这个有明确的时间吗？什么时候能发布支持bolt1.5的版本？

**Comment by QilongZhang** [comment]
> @QilongZhang 这个有明确的时间吗？什么时候能发布支持bolt1.5的版本？

我建议是放在 SOFABoot 3.1.6 版本管控。参考 @leizhiyuan 上面回复，RPC 需要适配 bolt 1.5 不兼容变更带点。 @leizhiyuan  一起关注下，确定大概的发布时间。

**Comment by straybirdzls** [comment]
确定相关改动放到 3.2.0 中
