### ISSUE TITLE
子模块初始化将父容器的相关Processor都注册到子容器的问题

### ISSUE THREAD

**Issue by TomorJM** [sofastack/sofa-boot#442]
![image](https://user-images.githubusercontent.com/11410549/60315339-c757a780-9998-11e9-86b2-f89398be5e90.png)
![image](https://user-images.githubusercontent.com/11410549/60315362-e0605880-9998-11e9-9997-edb214fdac12.png)
现在的情况是我在应用里(非模块)有一个BeanDefinitionRegistryPostProcessor接口的实现, 这个接口会在子模块初始化过程中重复调用(而这不是我希望发生的)
所以如图所示, 这样做的目的是什么? 不是很能理解, 望解答~

**Comment by QilongZhang** [comment]
每个模块上下文隔离，默认情况下，模块的都会有一个父上下文。 父上下文的所有 BeanPostProcessor 和 BeanFactoryPostProcessor 都会拷贝一份至子模块。背景是因为这个父上下文会扫描所有的 AutoConfiguration，姑且一般认为其中包含的所有 BeanPostProcessor 和 BeanFactoryPostProcessor 对其他模块都会生效，这里面确实可能会有一些问题。

再聊下你问题，如果不想让父上下文中的 BeanDefinitionRegistryPostProcessor 不生效，可能需要你手动判断当前上下文是否是父上下文(RootApplicationContext).

**Comment by TomorJM** [comment]
"父上下文的所有 BeanPostProcessor 和 BeanFactoryPostProcessor 都会拷贝一份至子模块"
这样做感觉有点不靠谱:
1. BeanPostProcessor等后置处理器要处理目的其实就是作用于context。在原本未接入sofa多模块的单应用场景是如此, 接入sofa模块化后更应该如此。每个上下文只需要关心自己context的bean加载. 框架要做的应该是通过某种机制(开发者不需要感知)将不同context的bean串联起来, 而不是将其他上下文的bean和processors都在当前上下文"重演"一遍。因为本身spring的这套加载和使用机制都非常灵活, sofa框架无法保证每个处理器都应该做什么不应该做什么。所以我觉得这里不应该在框架里强制"重演一遍"父上下文的处理器
2. 你给的我的问题的解决方案是可行, 但是像上面说的一样, 不合理。代码这样处理也很难看。还有就是如果父上下文的processors是在其他第三方框架里面, 这个问题就更麻烦了=.=

**Comment by ScienJus** [comment]
单纯定义「一定共享给子模块」或是「完全不共享给子模块」可能都很难满足各种场景把？看代码逻辑，加个注解/配置来控制是否共享的逻辑会不会更好一些？

1. 一个全局配置控制默认是否共享 *PostProcessor
2. 通过注解控制每个 *PostProcessor 是否会共享给子模块
3. 通过 bean name 控制某个特定 *PostProcessor 是否共享给子模块

**Comment by QilongZhang** [comment]
@TomorJM @ScienJus  目前的强制处理可能会存在问题，添加配置也不失为一种可行的方案，尤其是二方包的 PostProcessor 只能通过配置的方式引入，这种做法无论是使用成本还是理解成本都会提高，我想也是当时开发者考虑到的。似乎这种方式是取自 Spring  Cloud 的设计，麻烦请 @caojie09 关注下此问题。

**Comment by caojie09** [comment]
> 父上下文的所有 BeanPostProcessor 和 BeanFactoryPostProcessor 都会拷贝一份至子模块

当时这么做只是为了拆箱即用，因为很多框架都会对 BeanPostProcessor 和 BeanFactoryPostProcessor 进行扩展，而子上下文是无法使用父上下文的 BeanPostProcessor 和 BeanFactoryPostProcessor 的，所以就只能拷贝一份至模块中，不然每增加一个 starter 后增加的 Processor 在模块中就都无法使用了。这么处理的确可能有问题，因为有些 Processor 是不需要共享的，可以增加一个配置避免拷贝。

**Comment by TomorJM** [comment]
感谢~
希望尽快修复或者有需要我可以提个fix~

**Comment by caojie09** [comment]
> 希望尽快修复或者有需要我可以提个fix~

@TomorJM 非常欢迎提个fix~

**Comment by TomorJM** [comment]
现给出如下解决方案, 一起讨论评估下, 部分参考 @ScienJus 的建议
1. 一个全局配置控制默认是否共享 *PostProcessor, 默认共享(跟现状保持一致)

- 提供过滤器接口, 具体实现需要使用者自定义, 需实现如下方法
- filterName: 过滤具体的beanName
- filterClass: 过滤具体的*PostProcessor的实现类

2. 若不需要共享, 则关闭*PostProcessor在子模块的拷贝

**Comment by TomorJM** [comment]
@QilongZhang @ScienJus @caojie09

**Comment by TomorJM** [comment]
这个项目是又烂尾了嘛=.=

**Comment by caojie09** [comment]
@TomorJM 抱歉，一直忘记回复这个issue了。目前这个项目是有在维护的，我们公司内部也有在使用，只是这个问题在公司内部没有遇到，所以一直没处理，如果可以的话能帮我们提个 fix 吗？

**Comment by caojie09** [comment]
@TomorJM 先说一声抱歉，这个项目是专门的团队在维护的，蚂蚁金服内部也使用这个框架，所以请千万别担心会无人维护。造成这样的误会，再次表达诚挚的歉意，也真诚的感谢你对于项目的热切关注

>  现给出如下解决方案, 一起讨论评估下, 部分参考 @ScienJus 的建议
> 1.  一个全局配置控制默认是否共享 *PostProcessor, 默认共享(跟现状保持一致)
> * 提供过滤器接口, 具体实现需要使用者自定义, 需实现如下方法
> * filterName: 过滤具体的beanName
> * filterClass: 过滤具体的*PostProcessor的实现类
> 2. 若不需要共享, 则关闭*PostProcessor在子模块的拷贝

现在默认是共享，如果不希望共享，是不是只要增加一个配置项，把不需要的共享的bean加到配置中就可以了，配置项比实现接口更灵活。

**Comment by caojie09** [comment]
参考了下 @ScienJus 的方案

>  单纯定义「一定共享给子模块」或是「完全不共享给子模块」可能都很难满足各种场景把？看代码逻辑，加个注解/配置来控制是否共享的逻辑会不会更好一些？
> 1. 一个全局配置控制默认是否共享 *PostProcessor
> 2. 通过注解控制每个 *PostProcessor 是否会共享给子模块
> 3. 通过 bean name 控制某个特定 *PostProcessor 是否共享给子模块

我觉得这个方案很灵活：
1. 一个全局配置可以打开或者关闭共享 *PostProcessor
2. 注解方式可以给 *PostProcessor 开发者使用，很可能就是 Starter 开发，他们在开发的时候知道自己的 *PostProcessor 是否需要共享，直接增加注解，让用户使用的时无需增加黑名单也可正常使用
3. 最后是支持在配置中增加复制配置项，针对一些存量 starter，控制某些特定 *PostProcessor 是否共享给子模块

**Comment by TomorJM** [comment]
> 参考了下 @ScienJus 的方案
> 
> > 单纯定义「一定共享给子模块」或是「完全不共享给子模块」可能都很难满足各种场景把？看代码逻辑，加个注解/配置来控制是否共享的逻辑会不会更好一些？
> > 
> > 1. 一个全局配置控制默认是否共享 *PostProcessor
> > 2. 通过注解控制每个 *PostProcessor 是否会共享给子模块
> > 3. 通过 bean name 控制某个特定 *PostProcessor 是否共享给子模块
> 
> 我觉得这个方案很灵活：
> 
> 1. 一个全局配置可以打开或者关闭共享 *PostProcessor
> 2. 注解方式可以给 *PostProcessor 开发者使用，很可能就是 Starter 开发，他们在开发的时候知道自己的 *PostProcessor 是否需要共享，直接增加注解，让用户使用的时无需增加黑名单也可正常使用
> 3. 最后是支持在配置中增加复制配置项，针对一些存量 starter，控制某些特定 *PostProcessor 是否共享给子模块

2、3结合可以分别解决是其他二方包开发者和使用者的诉求。
但是仔细想想第二个方案解决的场景, 假如说我是一个jar包(这里就叫他A)的开发者, 我为了让自己的某些自定义*PostProcessor不共享给接入了SOFABoot的应用的子容器, 我得使用这个注解, 这间接会导致我A包还要去依赖SOFABoot, 这明显不合理, 因为会导致其他依赖了我A包的非SOFABoot应用也间接依赖SOFABoot。所以我觉得这个场景实际上不太可能出现。

**Comment by caojie09** [comment]
> 但是仔细想想第二个方案解决的场景, 假如说我是一个jar包(这里就叫他A)的开发者, 我为了让自己的某些自定义*PostProcessor不共享给接入了SOFABoot的应用的子容器, 我得使用这个注解, 这间接会导致我A包还要去依赖SOFABoot, 这明显不合理, 因为会导致其他依赖了我A包的非SOFABoot应用也间接依赖SOFABoot。所以我觉得这个场景实际上不太可能出现。

@TomorJM 如果用第二个策略，的确会让 jar 包开发者导入 SOFABoot 依赖，但是我觉得从框架完整性来看，我们还是应该提高这个能力。

**Comment by TomorJM** [comment]
> > 但是仔细想想第二个方案解决的场景, 假如说我是一个jar包(这里就叫他A)的开发者, 我为了让自己的某些自定义*PostProcessor不共享给接入了SOFABoot的应用的子容器, 我得使用这个注解, 这间接会导致我A包还要去依赖SOFABoot, 这明显不合理, 因为会导致其他依赖了我A包的非SOFABoot应用也间接依赖SOFABoot。所以我觉得这个场景实际上不太可能出现。
> 
> @TomorJM 如果用第二个策略，的确会让 jar 包开发者导入 SOFABoot 依赖，但是我觉得从框架完整性来看，我们还是应该提高这个能力。

嗯, 有这个必要。我将从以上思路做个Fix, 随时保持联络~

**Comment by caojie09** [comment]
> 嗯, 有这个必要。我将从以上思路做个Fix, 随时保持联络~
> ps:有啥开发者群嘛,或者Gitter Channel之类的?

可以加钉钉群: 23390449。
