### ISSUE TITLE
Does anyone resent this kind of xml?

### ISSUE THREAD

**Issue by wangwanchao** [sofastack/sofa-boot#448]
面对sofa-rpc这种xml配置方式，没有人反感吗？类似于dubbo的配置方式，写起来啰哩啰嗦，不知道究竟有多好，值得造这么一个轮子

**Comment by ujjboy** [comment]
Hi @wangwanchao, XML is just one of many ways to program, you can also use [Annotation](https://www.sofastack.tech/projects/sofa-rpc/programing-sofa-boot-annotation/) or [native API](https://www.sofastack.tech/projects/sofa-rpc/programing-sofa-boot-api/) of SOFARPC.
