### ISSUE TITLE
Jvm communication fails under the same process

### ISSUE THREAD

**Issue by bjmengyu** [sofastack/sofa-boot#449]
服务提供者jar里的代码
@SofaService(
    interfaceType = LogicflowVersionSyncService.class
)
public class LogicflowVersionSyncServiceImpl implements LogicflowVersionSyncService {

使用者
    @SofaReference(interfaceType = LogicflowVersionSyncService.class)
    private LogicflowVersionSyncService logicflowVersionSyncService;

异常：
EmptyTargetSource: no target class, static

**Comment by caojie09** [comment]
Can you provide a demo?
