### ISSUE TITLE
Project Code and organization would be refactored in 3.2.0

### ISSUE THREAD

**Issue by QilongZhang** [sofastack/sofa-boot#452]
在保证兼容性的情况下，我们计划将在 SOFABoot 3.2.0 重构工程代码和组织结构，整体改造目标有两个：

+ 尽可能使代码风格偏向 Spring boot
+ 参考 Spring，将 SOFARPC Starter  和 SOFATracer Starter 挪至 SOFABoot 工程。

#### 工程模块改造
```txt
.
└── sofa-boot-build
    ├── sofa-boot-project
    │   ├── sofa-boot
    │   ├── sofa-boot-actuator
    │   ├── sofa-boot-actuator-autoconfigure
    │   ├── sofa-boot-autoconfigure
    │   ├── sofa-boot-core
    │   │   ├── runtime-sofa-boot
    │   │   ├── isle-sofa-boot
    │   │   ├── healthcheck-sofa-boot
    │   │   ├── rpc-sofa-boot
    │   │   ├── tracer-sofa-boot
    │   │   └── test-sofa-boot
    │   │   
    │   ├── sofa-boot-parent
    │   ├── sofaboot-dependencies
    │   ├── sofa-boot-plugin
    │   │   ├── runtime-sofa-boot-plugin
    │   │   ├── rpc-sofa-boot-plugin
    │   │   └── tracer-sofa-boot-plugin
    │   │ 
    │   ├── sofa-boot-starters
    │   │   ├── runtime-sofa-boot-starter
    │   │   ├── isle-sofa-boot-starter
    │   │   ├── healthcheck-sofa-boot-starter
    │   │   ├── infra-sofa-boot-starter
    │   │   ├── test-sofa-boot-starter
    │   │   ├── rpc-sofa-boot-starter
    │   │   └── tracer-sofa-boot-starter
    │   │
    │   └── sofa-boot-tools
    │       └── sofa-boot-gradle-plugin
    │
    └── sofaboot-samples
        ├── sofaboot-sample
        ├── ... 
        └── sofaboot-sample-with-rpc
```

相较于之前的模块组织方式，我们参考了 Spring Boot 官方文档建议:

+ [Creating Your Own Auto-configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html)
+ [Building On Spring Boot](https://github.com/spring-projects/spring-boot/wiki/Building-On-Spring-Boot)

除了遵循上述开发建议之外，本次改造将 SOFARPC Starter 以及 SOFATracer Starter 相关代码挪至 SOFABoot 工程，这样做的原因有两点：

+ 避免工程分散各处，所有 Starter 走一个发布流程
+ 核心包和Starter分离，比如 tracer-core 和 tracer starter, 避免因为 starter 升级导致 core 包升级

**注意点**
+ SOFARPC starter 同步分支为 6.0.4-SNAPSHOT (确保所有 commit 均已被 cherry-pick)
+ SOFATracer starter 同步分支为 3.0.5

**Comment by ScienJus** [comment]
> 将 SOFARPC Starter 挪至 SOFABoot 工程 

totally agree!

PS：为什么 sofa-boot-actuator 在最顶层以及有一个单独的 autoconfigure？

**Comment by chpengzh** [comment]
springboot的starter每个模块是同一份代码不同依赖；我看这里拆分了core，在starter那里是只引用自己core实现，还是说全部都会引用啊。

**Comment by chpengzh** [comment]
还有一个问题，如果我没有理解错，目前healthcheck应该拓展了actuator的功能，可不可以只保留一个模块呢

**Comment by ScienJus** [comment]
> 我看这里拆分了core，在starter那里是只引用自己core实现，还是说全部都会引用啊。

@chpengzh  一般我比较熟悉的做法是：

1. 把所有和 autoconfig 加载逻辑无关的代码都放在 core 里
2. 把多个 core 的 spring boot 加载逻辑可以都写在同一个 autoconfig 里，用 conditional 条件化加载
3. starter 只是 pom 集合，一般一个项目的 starter 只负责将 autoconfig（可以是公共的）以及 core（对应的）引入到项目中

**Comment by chpengzh** [comment]
@ScienJus 嗯，大概就是这个意思 xxx-boot 本来就应该是一个条件加载引用的垃圾堆，拆分了之后如果有多个模块都要用到同一个bean，写的时候就要怀疑人生了。

**Comment by chpengzh** [comment]
还有如果有个starter-all的话应该会很受欢迎

**Comment by QilongZhang** [comment]
> > 将 SOFARPC Starter 挪至 SOFABoot 工程
> 
> totally agree!
> 
> PS：为什么 sofa-boot-actuator 在最顶层以及有一个单独的 autoconfigure？

感谢 @ScienJus 回复。 
SOFABoot 提供了若干 endpoint，放在 sofa-boot-actuator 中，这两个模块参考了 Spring Boot 的设计. PR 已提，欢迎指正。

**Comment by chpengzh** [comment]
soga, 原来autoconfig部分还是统一放在一起的，我理解错了

**Comment by wangyjx** [comment]
3.2有没有预计的发布时间?
