### ISSUE TITLE
Multi-module application of sofa boot

### ISSUE THREAD

**Issue by mygitdds** [sofastack/sofa-boot#458]
I used sofa boot's multi-module application, but boot appeared

  ├─ com.swallowBirds.businessSystem.dal-commodity
  ├─ com.swallowBirds.businessSystem.biz-commodity
  ├─ com.swallowBirds.businessSystem.dal-demand
  ├─ com.swallowBirds.businessSystem.biz-demand
  ├─ com.swallowBirds.businessSystem.dal-member
  ├─ com.swallowBirds.businessSystem.biz-member
  ├─ com.swallowBirds.businessSystem.dal-shop
  ├─ com.swallowBirds.businessSystem.biz-shop
  ├─ com.swallowBirds.businessSystem.dal-user
  ├─ com.swallowBirds.businessSystem.biz-user
  └─ com.swallowBirds.businessSystem.webflux-business

2019-07-28 15:51:32,400 INFO  main                             - ++++++++++++++++++ SpringContextInstallStage of testSofaboot End +++++++++++++++++
2019-07-28 15:51:32,400 INFO  main                             - ++++++++++++++++++ ModuleLogOutputStage of testSofaboot Start +++++++++++++++++
2019-07-28 15:51:32,401 INFO  main                             - 
Spring context initialize success module list(0) >>>>>>> [totalTime = 0 ms, realTime = 0 ms]

Spring context initialize failed module list(0) >>>>>>>

Spring bean load time cost list(0) >>>>>>> [totalTime = 0 ms, realTime = 0 ms]

The context in the module is not started. What's the matter?

**Comment by caojie09** [comment]
Have you added sofa-module.properties file？
