### ISSUE TITLE
The bean 'sampleService'  could not be registered.

### ISSUE THREAD

**Issue by jimchou800** [sofastack/sofa-boot#463]
在运行`sofaboot-samples` 的 `sofaboot-sample-standard-web` 模块 `SOFABootWebApplication` 发生了一个异常:

```
The bean 'sampleService', defined in class path resource [com/alipay/sofa/runtime/test/ServiceAopTest$ServiceAopTestConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alipay/sofa/runtime/test/ComponentManagerTest$ComponentManagerTestConfiguration.class] and overriding is disabled.
```
从错误信息初步定位: ServiceAopTest 和 ComponentManagerTest 有重名的bean ，但是这两个类是在 测试源包 `src/test/java` 下的，不应该被扫描到吧

**Comment by jimchou800** [comment]
The bean 'sampleService', defined in class path resource [com/alipay/sofa/runtime/test/ServiceAopTest$ServiceAopTestConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [com/alipay/sofa/runtime/test/ComponentManagerTest$ComponentManagerTestConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true

-------------------------------
在 STS 下直接运行 sofaboot-sample-standard-web 的`com.alipay.sofa.SOFABootWebApplication` main方法 报这个错误，但是在idel运行正常

**Comment by caojie09** [comment]
试了下，master分支是没有这个问题的，这个issue暂时先关闭哈~
