### ISSUE TITLE
install module failed？

### ISSUE THREAD

**Issue by grindwheel** [sofastack/sofa-boot#464]
![image](https://user-images.githubusercontent.com/10232714/62762627-22161000-babc-11e9-8d89-6963ff47c315.png)

**Comment by glmapper** [comment]
@grindwheel 能提供其他一些信息吗？比如 /sofa-ark 或者  /sofa-runtime 下的错误日志，如果能够提供一个与场景相似的  simple demo 也可以。

**Comment by grindwheel** [comment]
@glmapper 这个日志就是/sofa-ark的日志

**Comment by grindwheel** [comment]
@glmapper 这个我们已经是线上应用了，但是偶尔会出现这个问题

**Comment by glmapper** [comment]
> @glmapper 这个我们已经是线上应用了，但是偶尔会出现这个问题

能看到 异常的 cause by 吗

**Comment by grindwheel** [comment]
@glmapper 没有cause by 呢，sofa-ark日志就这个
