### ISSUE TITLE
SofaBootHealthCheckInitializer lifecycle error

### ISSUE THREAD

**Issue by antergone** [sofastack/sofa-boot#465]
在代码结构重构以前的版本都有这个问题.

`com.alipay.sofa.healthcheck.initializer.SofaBootHealthCheckInitializer `这个类的声明周期要早于 `CommonLoggingApplicationListener`监听的`ApplicationEnvironmentPreparedEvent`，所以这里面的配置复写还没有生效，`SofaBootHealthCheckLoggerFactory.getLogger`拿到的都是默认配置，或者错误配置。
其他地方没有细心检查，估计也存在类似问题

**Comment by alaneuler** [comment]
This issue is fixed in refactor versions of SOFABoot. And version 2.x is no longer maintained.
