### ISSUE TITLE
Maven plugin spring-boot-maven-plugin error when importing this project to idea

### ISSUE THREAD

**Issue by ggndnn** [sofastack/sofa-boot#477]
I got an error when importing sofa-boot to idea (2019.2), though maven compile is ok.

`Cannot resolve plugin org.springframework.boot:spring-boot-maven-plugin:<unknown>`

Is it appropriate to add a pluginManagement to sofa-boot-samples pom.xml or any suggestion to solve this error? e.g.

```
<pluginManagement>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <version>2.1.8.RELEASE</version>
        </plugin>
    </plugins>
</pluginManagement>
```

By the way, why is master branch sofa-boot version is 3.2.0 now, but not something like 3.2.1-SNAPSHOT?

**Comment by caojie09** [comment]
spring-boot-dependencies has defined spring-boot-maven-plugin version: https://github.com/spring-projects/spring-boot/blob/v2.1.0.RELEASE/spring-boot-project/spring-boot-dependencies/pom.xml#L3041

now master branch is 3.2.1-SNAPSHOT.

**Comment by ggndnn** [comment]
ok, thank you.
