### ISSUE TITLE
JVM Reference[interface com.alipay.sofa.isle.sample.SampleJvmService#] can not find the corresponding JVM service.

### ISSUE THREAD

**Issue by a1207701687** [sofastack/sofa-boot#484]
你好，我用的sofaboot-sample-with-isle这个例子，gradle，启动后访问报错，还需要改什么吗

**Comment by khotyn** [comment]
你是怎么启动的呢？我这里跑了一下，没有问题。

**Comment by a1207701687** [comment]
在sofa-boot-run的子工程中，以java application的方式启动的 类 ApplicationRun，eclipse的。 什么都没改，直接gradle编译完，运行就不行

**Comment by a1207701687** [comment]
这是报错的截图
![图片](https://user-images.githubusercontent.com/13097076/66536375-47bca580-eb4f-11e9-95c5-246ed6f0c99d.png)

**Comment by codemongkey** [comment]
这个问题解决了吗？我也遇到了

**Comment by glmapper** [comment]
@a1207701687 @codemongkey we have migrate guides to https://github.com/sofastack-guides/sofa-boot-guides. just startup by ApplicationRun, and try it again.

**Comment by sxc9870** [comment]
@glmapper  还是不行，用的STS，启动的时候META-INF/spring/下面的xml没有被扫到，需要额外配置什么吗？
Still can't. with STS, the XML under meta-inf / spring / is not scanned when it is started. Do you need to configure anything else?
