### ISSUE TITLE
ParserUtils 中 Boolean.getBoolean 疑 是 Boolean.parseBoolean 的 误 写

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [sofastack/sofa-boot#498]
Boolean.getBoolean疑是Boolean.parseBoolean的误写，导致一直返回false
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java#L56
同样的场景，下文使用的是Boolean.parseBoolean
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java#L58

**Comment by khotyn** [comment]
是的， @QiAnXinCodeSafe 可以直接提一个 PR 吗？

**Comment by QiAnXinCodeSafe** [comment]
好的，后续提交
