### ISSUE TITLE
a single-threaded local variable StringBuffer, can be replaced by a non-thread-safe StringBuilder

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [sofastack/sofa-boot#499]
以下2个文件中的单线程局部变量StringBuffer可以使用非线程安全的StringBuilder替代
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/common/xmap/Path.java#L62
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/rpc-sofa-boot/src/main/java/com/alipay/sofa/rpc/boot/container/ProviderConfigContainer.java#L205

**Comment by ujjboy** [comment]
It makes sense. can you submit your PR to fix it?

**Comment by QiAnXinCodeSafe** [comment]
好的，后续提交
