### ISSUE TITLE
Run the sample-isle project in idea, module does not install

### ISSUE THREAD

**Issue by codemongkey** [sofastack/sofa-boot#503]
![image](https://user-images.githubusercontent.com/43233795/66914276-09d8e900-f049-11e9-9a10-c00704dc8ab1.png)
ru如图所示，明明有module could install,但是不会去install

**Comment by caojie09** [comment]
你跑的是哪个分支呢，我用 master 分支试了下，运行是正常的：

![image](https://user-images.githubusercontent.com/38058846/66920388-bf119e00-f055-11e9-827c-d7306fe64ebb.png)

**Comment by codemongkey** [comment]
@caojie09 你好，那应该是项目导入的问题，可否说明一下你是怎么执行的吗？
我是这么做的，源码下载后用idea(2019)打开sofaboot-sample-with-isle工程，如下图所示：
![image](https://user-images.githubusercontent.com/43233795/66972831-692a0e00-f0c8-11e9-8e62-df910a4756f2.png)

修改源码中parent标签，然后run sofa-boot-run下的ApplicationRun

**Comment by caojie09** [comment]
> 修改源码中parent标签，然后run sofa-boot-run下的ApplicationRun

@codemongkey 为什么要改 parent 版本号？如果你想看 3.1.3 版本示例，你可以使用 v3.1.3 这个 tag。

**Comment by codemongkey** [comment]
@caojie09 
![image](https://user-images.githubusercontent.com/43233795/66989447-f6845700-f0f6-11e9-80e7-1098424826f8.png)
我改<parent>是因为原来的sofaboot-samples找不到，并且sofaboot-dependencies的最新版本是3.1.3。但我已经在settings.xml中加入所要求的profile了
![image](https://user-images.githubusercontent.com/43233795/66989614-46631e00-f0f7-11e9-9a5e-59eb670ff844.png)
如果把整个工程导入idea
![image](https://user-images.githubusercontent.com/43233795/66989892-ca1d0a80-f0f7-11e9-9dd6-12f794f0e32b.png)
运行application会有
![image](https://user-images.githubusercontent.com/43233795/66989956-e325bb80-f0f7-11e9-8a1e-8b68a29835dc.png)

所以我想请教一下您，sofaboot-sample-with-isle工程是怎么导入运行的。因为我知道sofaboot有三个版本 
![image](https://user-images.githubusercontent.com/43233795/66990097-25e79380-f0f8-11e9-9a44-532b6dc462d7.png)

**Comment by caojie09** [comment]
@codemongkey 看下这里的 [sample 工程](https://github.com/sofastack-guides/sofa-boot-guides)，我们刚把 sample 工程移到统一仓库。
