### ISSUE TITLE
In the case where the log print level is debug: When the parameter of the XXXservicemng method is map, Finish JVM service invoke, the service implementation is

### ISSUE THREAD

**Issue by honeyzhaoAliyun** [sofastack/sofa-boot#509]
在日志打印级别为debug的情况下：当XXXservicemng 方法的参数为map的时候，在JvmBinding Adapter 会去toString处理参数“，”处理拼装。但是在getCommonInvocationLog()方法里面 ，注意大括号｛0，1｝结果是｛a=1,b=2｝就报错了
在日志打印级别为info的情况下，不会报错

**Comment by caojie09** [comment]
duplicate issue.
