### ISSUE TITLE
In the case where the log print level is debug: when the parameter of the XXXservicemng method is map: Finish JVM service invoke, the service implementation is

### ISSUE THREAD

**Issue by honeyzhaoAliyun** [sofastack/sofa-boot#510]
在日志打印级别为debug的情况下：当XXXservicemng 方法的参数为map的时候，在JvmBinding Adapter 会去toString处理参数“，”处理拼装。但是在getCommonInvocationLog()方法里面 ，注意大括号｛0，1｝结果是｛a=1,b=2｝就报错了
在日志打印级别为info的情况下，不会报错
![图片](https://user-images.githubusercontent.com/10372081/67185881-66f1e780-f419-11e9-97c8-b7f2a9c83a88.png)

**Comment by caojie09** [comment]
什么报错，有堆栈吗？

**Comment by khotyn** [comment]
没有看明白，能够提供下详细的错误堆栈吗？

**Comment by khotyn** [comment]
没有看出具体的问题，暂时先把这个 Issue 关闭掉了，如果能够提供更多详细信息的话，请再打开这个 Issue， @honeyzhaoAliyun
