### ISSUE TITLE
Why doesn&#39;t the publish http service support the publish http service?

### ISSUE THREAD

**Issue by HuangSheng** [sofastack/sofa-boot#522]
```
   @SofaServiceBinding(bindingType = "")
```
使用注解发布服务时，bindingType 为什么不支持发布http服务？我看SOFARPC的API是支持http服务发布的，但是在使用注解时就不可以发布http服务了，是否可以添加支持？

![image](https://user-images.githubusercontent.com/2976373/68284211-0371e600-00b8-11ea-8e37-80dfc546ff7f.png)

**Comment by khotyn** [comment]
可以添加支持， @HuangSheng 你方便直接提交一个 PR 吗？

**Comment by HuangSheng** [comment]
> 可以添加支持， @HuangSheng 你方便直接提交一个 PR 吗？

我抽空提一个PR，加入http服务发布
