### ISSUE TITLE
springboot 2.1.11 对应的 sofaboot-dependencies 版本是多少

### ISSUE THREAD

**Issue by 95zz** [sofastack/sofa-boot#546]

**Comment by glmapper** [comment]
@95zz springboot 和 sofaboot 的版本关系请参阅：https://www.sofastack.tech/projects/sofa-boot/overview/

**Comment by 95zz** [comment]
好的。期待 支持 springboot 2.1.11.RELEASE

**Comment by glmapper** [comment]
> 好的。期待 支持 spring boot 2.1.11.RELEASE

请问 spring boot 2.1.11.RELEASE 是有什么你比较关注的特性吗?
