### ISSUE TITLE
关于代码格式化模板

### ISSUE THREAD

**Issue by leshalv** [sofastack/sofa-boot#562]
IDEA导入格式化模板后，试着全部格式化了一下，发现大部分格式都被更改了，只有少量格式没有被更改，我很疑惑，是我配置有问题，还是格式化模板有问题？
我是通过导入eclipse格式化模板方式导入的，导入后没有做额外操作。

**Comment by ujjboy** [comment]
try `mvn clean compile`

**Comment by pingfangushi** [comment]
https://www.pingfangushi.com/posts/46538/
https://www.pingfangushi.com/posts/57675/
嗯嗯知道怎么用了，偷偷记录了下哈哈哈哈。

**Comment by pingfangushi** [comment]
嗯嗯，知道怎么用了，偷偷记录了下哈哈哈哈。
https://www.pingfangushi.com/posts/46538/
https://www.pingfangushi.com/posts/57675/

**Comment by leshalv** [comment]
嗯嗯，知道怎么用了，偷偷记录了下哈哈哈哈。
https://www.pingfangushi.com/posts/46538/
https://www.pingfangushi.com/posts/57675/
