### ISSUE TITLE
Cannot use SOFARegistry after upgrading sofa-boot 3.2.1

### ISSUE THREAD

**Issue by HuangSheng** [sofastack/sofa-boot#566]
升级sofa-boot到3.2.1版本后，SOFARegistry无法使用，只能使用zk做注册中心。检查代码发现是SofaRpcAutoConfiguration 这个类在做注入注册中心处理器实现时添加了 @ConditionalOnMissingBean 注解，导致只注入了local、mesh和zk的处理器，其它注册中心的处理器没有注入。不知为何要做这个配置？如果要使用新版本的话需要如何修改？

**Comment by leizhiyuan** [comment]
临时可能需要用户 自己写一下这几个bean。按照pr中的修复。。
