### ISSUE TITLE
SofaBoot cannot specify virtual IP and port through environment variables

### ISSUE THREAD

**Issue by forsake0120** [sofastack/sofa-boot#588]
SofaBoot无法通过环境变量将virtualHost及virtualPort注册至注册中心（注册中心无法得知服务真实IP，只能获取虚拟机内部IP）

**Comment by leizhiyuan** [comment]
麻烦提供下复现步骤？

**Comment by forsake0120** [comment]
docker运行命令如下：
docker run -d -e TZ="Asia/Shanghai" -e PARAMS="-Dserver.port=8081 -Drpc_tr_port=28888 -Drpc_register_virtual_host=10.23.120.30" -p 8081:8081 -p 28888:28888 --net=host app
其中server.port, rpc_tr_port均生效，zk中看到服务方地址认为虚拟机内网地址，如下

bolt%3A%2F%2F172.17.0.1%3A28888%3Fversion%3D1.0%26accepts%3D100000%26appName%3Dfundop-flatform%26weight%3D100%26language%3Djava%26pid%3D8%26interface%3Dcom.xxx.xxx.facade.system.ShiroService%26timeout%3D3000%26serialization%3Dhessian2%26protocol%3Dbolt%26delay%3D-1%26dynamic%3Dtrue%26startTime%3D1581306160635%26id%3Drpc-cfg-3%26uniqueId%3D%26rpcVer%3D50505

SofaBootRpcProperties类未从环境变量中读取该变量
 public String getVirtualHost() {
        return StringUtils.isEmpty(virtualHost) ? getDotString(new Object() {
        }.getClass().getEnclosingMethod().getName()) : virtualHost;
    }

**Comment by leizhiyuan** [comment]
什么版本的sofaboot？

**Comment by leizhiyuan** [comment]
从你的数据上看，Drpc_tr_port=28888  这个不是生效了么？

```
bolt%3A%2F%2F172.17.0.1%3A28888
```

**Comment by forsake0120** [comment]
> 什么版本的sofaboot？
> 
> 另外 rpc_register_virtual_host 这个是从哪里看到的？我们好像没用过这个key

1. sofaboot版本是3.1.5。目前master上的这部分代码我也看过
2. SofaOptions.CONFIG_RPC_REGISTER_VIRTUAL_HOST
3. SofaBootRpcProperties中部分变量先从环境变量中获取，部分没有（virtualHost，virtualPort均没有）
4. virtualHost, virtualPort会在ServerConfigContainer中写入到ServerConfig中
5. 在ZookeeperRegistry中会从ServerConfig中获取该地址并拼成URL写入zk。如果没有虚拟地址，则写入真实IP等（RegistryUtils.converProviderToUrls）
![image](https://user-images.githubusercontent.com/24488347/74205073-aa19e400-4cb0-11ea-83be-086136347d26.png)
还请供参考，非常感谢

**Comment by forsake0120** [comment]
> 从你的数据上看，Drpc_tr_port=28888 这个不是生效了么？
> 
> ```
> bolt%3A%2F%2F172.17.0.1%3A28888
> ```
事实上，这个端口是通过变量 -Drpc_tr_port=28888 生效的，虚拟机内也用这个端口启动。virtualHost和virtualPort都没有生效。

刚刚我测试了一下，修改SofaBootRPCProperties中增加从环境变量中获取，即可生效。

**Comment by leizhiyuan** [comment]
看了一下，用法应该是这个 

https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/ 你试试

-Dcom.alipay.sofa.rpc.virtual.host # virtual host
-Dcom.alipay.sofa.rpc.virtual.port # virtual端

**Comment by forsake0120** [comment]
> 看了一下，用法应该是这个
> 
> https://www.sofastack.tech/projects/sofa-rpc/application-rpc-config/ 你试试
> 
> -Dcom.alipay.sofa.rpc.virtual.host # virtual host
> -Dcom.alipay.sofa.rpc.virtual.port # virtual端

确实没问题，非常感谢，这个issue烦请关闭了谢谢

**Comment by leizhiyuan** [comment]
好的～

**Comment by forsake0120** [comment]
不好意思还有一个问题。
-Dcom.alipay.sofa.rpc.virtual.port # virtual端
这个变量我看在zk下没有生效，测试截图如下：
![image](https://user-images.githubusercontent.com/24488347/74209127-6aa7c380-4cc1-11ea-9ea0-c9ebd03a01fa.png)
![image](https://user-images.githubusercontent.com/24488347/74209152-8317de00-4cc1-11ea-950c-f9cf741adb3b.png)
我看了下代码，发现只有在SofaRegistryHelper中从serverConfig中读了virtualPort，ZooKeeper中貌似没读。
还想请教一下还有其他办法通过环境变量修改virtualPort么？

**Comment by leizhiyuan** [comment]
https://github.com/sofastack/sofa-rpc/pull/826 5.6.4已经修复了 ，暂时还没有发布。

如果急需，可能需要先覆盖一下 ZookeeperRegistry 这个类。

**Comment by forsake0120** [comment]
> [sofastack/sofa-rpc#826](https://github.com/sofastack/sofa-rpc/pull/826) 5.6.4已经修复了 ，暂时还没有发布。
> 
> 如果急需，可能需要先覆盖一下 ZookeeperRegistry 这个类。

收到，非常感谢
