### ISSUE TITLE
I don't understand the JVM service release and reference in the sofaboot tutorial

### ISSUE THREAD

**Issue by ghost** [sofastack/sofa-boot#589]
教程地址 https://www.sofastack.tech/projects/sofa-boot/module-service/

使用 @SofaService 注解发布服务时，需要在实现类上打上 @SofaService 注解；在 Spring Boot 使用 Bean Method 创建 Bean 时，会导致 @Bean 和 @SofaService 分散在两处，而且无法对同一个实现类使用不同的 unique id。因此自 SOFABoot v2.6.0 及 v3.1.0 版本起，支持 @SofaService 作用在 Bean Method 之上，例如：

```
@Configuration
public class SampleSofaServiceConfiguration {
    @Bean("sampleSofaService")
    @SofaService(uniqueId = "service1")
    SampleService service() {
        return new SampleServiceImpl("");
    }
}
```
会导致 @Bean 和 @SofaService 分散在两处，而且无法对同一个实现类使用不同的 unique id

对于这个分散在两处能给一个例子吗??  

而且无法对同一个实现类使用不同的 unique id, 这句话我也不是很理解.

还有就是 @SofaService 注解

SOFABoot 还提供了 Annotation 的方式来发布和引用 JVM 服务。通过 Annotation 方式发布 JVM 服务，只需要在实现类上加一个 @SofaService 注解即可.

也就是说 @SofaService 是发布 jvm 服务的, 但是 在 SOFARPC 教程的 SOFABoot 环境注解使用 文章 https://www.sofastack.tech/projects/sofa-rpc/programing-sofa-boot-annotation/ 中说: 如果要发布一个 RPC 服务. 我们只需要在 Bean 上面打上@SofaService注解.指定接口和协议类型即可.

我可以理解为 指定了协议就是发布 RPC 服务, 没有指定就是发布 JVM 服务吗?

我是一个小菜鸟.

**Comment by alaneuler** [comment]
这里的散落在两处是指，一处打在 bean class 上，一处在 bean method 上（这个好理解），例如
```
@SofaService
public class MyBean implement SomeInterface {
    ...
}
```
