### ISSUE TITLE
How to achieve lossless when service restart?sofa-boot has achieved this function

### ISSUE THREAD

**Issue by SongYintao** [sofastack/sofa-boot#591]
In a production environment, a lossless release occurs when the service is republished. After the old service instance goes offline, traffic detection will be performed. After no traffic, the current service (containerization scenario) will be destroyed or the service will be restarted. Does sofa-boot support this lossless feature? Or the function of flow detection?

**Comment by khotyn** [comment]
You mean graceful shutdown?

**Comment by alaneuler** [comment]
This issuing is closed due to long-time inactivity.
