### ISSUE TITLE
3.4.0版本按照快速入门配置无法启用SOFA特性

### ISSUE THREAD

**Issue by yy1098029419** [sofastack/sofa-boot#653]
在3.4.0版本按照快速入门配置，能立刻启动成功，但是没有加载到SOFA相关特性，version链接也无法访问。换成3.2.1版本时没有问题。

**Comment by alaneuler** [comment]
只是切换一个版本号吗？你说的 SOFA 相关特性指的是啥呢

**Comment by cycle2zhou** [comment]
貌似好像3.4版本会造成一些注解失效，我在3.2.1版本自动配置没问题，升级到3.4的时候就发现配置没自动注入，最后测试发现时注解没生效，我这边是测试到@ConditionalOnMissingBean这个注解失效，我猜想应该不止一个注解受到影响

**Comment by alaneuler** [comment]
从 3.2.1 到 3.4 并没有自动配置逻辑的改动，能提供一下你的测试样例吗？

**Comment by yy1098029419** [comment]
@alaneuler 抱歉，一直忘记回复。目前我再次尝试3.4.0版本时，发现已经可以正常使用了。
