### ISSUE TITLE
About native compilation

### ISSUE THREAD

**Issue by swqmaven** [sofastack/sofa-boot#669]
之前看到一篇文章关于本地编译的问题，简单介绍了下在用这种方式来提高app的运行速度及资源占用情况。想问下sofa-boot是如何做到的？是否已经开源了相关组件或者使用了类似的技术。

**Comment by ujjboy** [comment]
@swqmaven 是哪篇文章呢？ 你是指的静态编译？

**Comment by swqmaven** [comment]
> @swqmaven 是哪篇文章呢？ 你是指的静态编译？

 对，他那篇文章就是提到大量使用本地静态编译，以此来应对高流量下的弹性伸缩资源利用效率等，就是想知道具体是采用哪种方案来做的。graalvm我倒是知道但是针对spring boot的支持还不是很好持续改进中

**Comment by ujjboy** [comment]
方便的话，你可以找下文章链接。  sofa-boot 基于 GraalVM 和内部的 alijdk 做过一些实践。

**Comment by swqmaven** [comment]
> 方便的话，你可以找下文章链接。 sofa-boot 基于 GraalVM 和内部的 alijdk 做过一些实践。

我找下，是在头条一篇偶然看到的，关于这方面sofa-boot GraalVM实践有详细的资料经验分享吗？

**Comment by khotyn** [comment]
@swqmaven 这部分没有开源的计划哦，有一篇文章有大概的介绍：https://medium.com/graalvm/static-compilation-of-java-applications-at-alibaba-at-scale-2944163c92e
