### ISSUE TITLE
when logging.level  is debug, should not be to execute getCommonInvocationLog

### ISSUE THREAD

**Issue by glmapper** [sofastack/sofa-boot#691]
![image](https://user-images.githubusercontent.com/35319286/90858922-bf876d80-e3b9-11ea-9f8c-03388a3143c1.png)

在测试中发现，当调用 jvm 时，如果此 jvm 的方法参数值数据较大，在执行 StringBuilder#append 时耗时影响也会较大。因此在明确是在 debug 级别才打印日志的情况下，不应该再去执行 getCommonInvocationLog 方法

**Comment by hermeshephaestus** [comment]
OK, I will solve this question!

**Comment by alaneuler** [comment]
It seems that this issue is already fixed in current SOFABoot.
