### ISSUE TITLE
关于ClassLoader的问题

### ISSUE THREAD

**Issue by dwj1979** [sofastack/sofa-boot#729]
我在将原来的基于SpringBoot的项目升级到使用Sofa，原本的SpringBoot项目中（使用Tomcat的Servlet容器），classLoader 是Launcher$AppClassLoader，ClassUtils.isPresent(），但是在引入Sofa以后，classLoader 变为ClassLoader$AppClassLoader，
这两个classLoader有什么区别

**Comment by dwj1979** [comment]
补充说明：代码在Idea InteliJ开发工具中启动就不报错，打包后执行就报错

**Comment by alaneuler** [comment]
引入 sofaboot 之后，classloader 不会变得；我本地实验了下，还是 Launcher$AppClassLoader 呢

**Comment by dwj1979** [comment]
我用的sofa-boot-guids工程测试的，

@ImportResource({ "classpath*:rpc-starter-example.xml" })
@SpringBootApplication
public class DemoApplication {


    public static void main(String[] args) {
        ApplicationContext applicationContext = SpringApplication.run(DemoApplication.class, args);
        **DemoApplication.class.getClassLoader();**
在这个位置获得的断点，就是ClassLoader$AppClassLoader，

**Comment by alaneuler** [comment]
确认一下，你的 JDK 版本没变过吧 @dwj1979

**Comment by dwj1979** [comment]
用的测试工程，我本地的JDK11.0.2

**Comment by alaneuler** [comment]
猜测是你在测试的时候用了不同的 JDK 版本，JDK 8 上面是 Launcher$AppClassLoader，JDK 9 以上是 ClassLoader$AppClassLoader。这个没什么区别
