### ISSUE TITLE
Schema location change to subdomain.

### ISSUE THREAD

**Issue by ujjboy** [sofastack/sofa-boot#73]
Now the schema location is like this `http://sofastack.io/schema/sofaboot`. But `sofastack.io` is an apex domain. `sofastack.io` is managed by Alipay DNS server, which not supports setting an apex domain.

Maybe we can change the location to a `www` subdomain, like `http://www.sofastack.io/schema/sofaboot`.

I noticed that `Spring` did it like this too:
- `http://www.springframework.org/schema/beans`

**Comment by khotyn** [comment]
Is this will cause some compatible problem?

**Comment by ujjboy** [comment]
If both two domain is specified, I think there should be no problem.

Spring.handlers:
```ini
http\://sofastack.io/schema/sofaboot=com.alipay.sofa.infra.config.spring.namespace.handler.SofaBootNamespaceHandler
http\://www.sofastack.io/schema/sofaboot=com.alipay.sofa.infra.config.spring.namespace.handler.SofaBootNamespaceHandler
```

Spring.schemas:
```
http\://sofastack.io/schema/sofaboot.xsd=META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/sofaboot.xsd
http\://www.sofastack.io/schema/sofaboot.xsd=META-INF/com/alipay/sofa/infra/config/spring/namespace/schema/sofaboot.xsd
```

**Comment by alaneuler** [comment]
It seems that the apex domain won't cause compatibility issue, but changing it from `sofastack.io` to `www.sofastack.io` makes more compliance.
