### ISSUE TITLE
添加索引扫描依赖，提升启动速度

### ISSUE THREAD

**Issue by snac21** [sofastack/sofa-boot#735]
sofaboot基于spring5.0，
spring5.0提供了如下依赖，可提升启动速度    
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context-indexer</artifactId>
            <optional>true</optional>
        </dependency>

**Comment by alaneuler** [comment]
Good point, spring-context-indexer is a dependency that Spring Boot or SOFA boot application should care and add.

**Comment by snac21** [comment]
when I run sofaboot,it takes me almost 1 min to startup ,
 and this dependency  save me about half of it，if your team takes this suggestion，
 please remind me，anyway，I guesst it will save we developers hundreds and millions of time in the few years， 
 
 best regards

*Company: 邦道科技
*Address: Wuxi,China
*Website: https://www.bangdao-tech.com
*Using components: sofaboot
*Email: haibin.chen@bangdao-tech.com
            snac21@163.com

**Comment by alaneuler** [comment]
BTW, how many beans does your system have @snac21

**Comment by snac21** [comment]
enough，y？

**Comment by alaneuler** [comment]
We're considering updating the SOFABoot demo to include spring-context-indexer dependency

**Comment by snac21** [comment]
sounds like good
