### ISSUE TITLE
SofaRuntimeConfigurationProperties' using of this.getClass().getClassLoader() as key has bug in it

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-boot#767]
SofaRuntimeConfigurationProperties is exported by SOFA Runtime plugin in Ark environment, so the keys of configuration map are always the same. Like:
![image](https://user-images.githubusercontent.com/8054939/99486887-0debde80-29a0-11eb-940f-141a4d9ff618.png)

**Comment by HzjNeverStop** [comment]
has it be fixed？

**Comment by alaneuler** [comment]
scheduled in 3.6.1
