### ISSUE TITLE
Require-Module 有多个的时候，是逗号隔开还是另加一行？

### ISSUE THREAD

**Issue by horsy945** [sofastack/sofa-boot#773]
你好，一个sofa-module 依赖另外两个module 的时候，配置的格式是怎样的？

例如：com.alipay.sofa.service-consumer 依赖 com.alipay.sofa.service-provider 及 com.alipay.sofa.consumer-dao 时，配置是这样的吗？
`Module-Name=com.alipay.sofa.service-consumer
Require-Module=com.alipay.sofa.service-provider,com.alipay.sofa.consumer-dao`

**Comment by glmapper** [comment]
https://www.sofastack.tech/projects/sofa-boot/sofaboot-module/
