### ISSUE TITLE
项目路径中包含中文的时候发布服务会报 can not find the corresponding JVM service

### ISSUE THREAD

**Issue by leijieallstar** [sofastack/sofa-boot#777]
项目路径中包含中文的时候发布服务会报  can not find the corresponding JVM service
截取了一段日志：
JVM Reference[interface com.alipay.sofa.isle.sample.SampleJvmService#serviceClientImpl] can not find the corresponding JVM service. Please check if there is a SOFA deployment publish the corresponding JVM service. If this exception occurred when the application starts up, please add Require-Module to SOFA deployment's MANIFEST.MF to indicate the startup dependency of SOFA modules.

如果去掉中文就没问题了，可能也不算是bug， 写下来给大家一个提醒。

**Comment by alaneuler** [comment]
#782 也会修复这个问题~
