### ISSUE TITLE
sofa-boot-3.6.0与sofa-common-tools冲突

### ISSUE THREAD

**Issue by yuanzhipeng** [sofastack/sofa-boot#789]
sofa-boot-3.6.0中 在sofa-boot-project\sofaboot-dependcies\pom中依赖了sofa-common-tools-1.3.0.jar但是在githuab上并未发布.手动降低到1.2.2版本     runtime-sofa-tools中AsyncTaskExecutor.class line 83 行   缺少默认构造器. 还是希望能早点提交新的版本依赖

**Comment by elseifer** [comment]
> sofa-boot-3.6.0中 在sofa-boot-project\sofaboot-dependcies\pom中依赖了sofa-common-tools-1.3.0.jar但是在githuab上并未发布.手动降低到1.2.2版本 runtime-sofa-tools中AsyncTaskExecutor.class line 83 行 缺少默认构造器. 还是希望能早点提交新的版本依赖

当前（12月29日）为止3.6.0还在开发阶段，没有正式发布，建议使用稳定版本。如果你调试代码，也建议切换到3.4.6的tag

**Comment by HzjNeverStop** [comment]
This question is fixed, you can verify it
