### ISSUE TITLE
Sofaboot模块内部的业务组件必须依赖xml定义bean方式才能隔离上下文？

### ISSUE THREAD

**Issue by lduffy69** [sofastack/sofa-boot#802]
如题，目前sofaboot模块的对外发布jvm/rpc服务，无论注解，api,xml三种方式都需要META-INF/spring/*.xml中定义bean，而内部组件beanId定义也需要频繁更新xml实现sofaboot的上下文隔离，Spring原生注解方式【@Component/@Service】定义内部业务组件，在Root Context下依然有可能产生beanId冲突问题，请问如何在使用独立上下文的需求下更方便地定义内部组件~

**Comment by alaneuler** [comment]
并不是这个意思哦。

xml 是模块隔离的入口，SOFA 会主动读取 META/spring/ 下的 xml 文件，作为这个模块的上下文 bean 定义来源。但是需要注意的是，xml 里面不仅能配置 bean，还可以配置 Spring 上下文，比如你提到的 componentscan：

```xml
<context:component-scan base-package="com.package.of.this.module" />
```

这样配置之后，你就可以在模块里面用注解定义 Spring bean 和 SOFA 服务了；有很重要的一点：这里配置的 component scan 不要扫到别的模块的 bean，否则可能会有冲突，因此 package 的定义要非常注意。

**Comment by lduffy69** [comment]
我思维僵硬了，其实就是一定程度上可以极大避免beanId冲突，但是模块，主应用的包定义依然要规范，多谢解答~
