### ISSUE TITLE
Any plan to upgrade to Spring Boot 2.4.X?

### ISSUE THREAD

**Issue by wangyjx** [sofastack/sofa-boot#811]
Since Spring Cloud Alibaba is going to release its first version that is compatible with Spring Cloud 2020.
I wonder whether you have similar plan to upgrade to boot 2.4.X or Spring Cloud 2020.X ? ( I know you will upgrade to boot 2.3.9 in 3.7 release)

I understand 2.4.X has lots of breaking changes and lots of work to do

**Comment by ujjboy** [comment]
Maybe upgrade SpringBoot to 2.4.x in v3.9.0 in August 2021.

**Comment by wangyjx** [comment]
Thanks for the information
