### ISSUE TITLE
sofaBootV3.6.0对应的SpringBoot的版本是多少？

### ISSUE THREAD

**Issue by bbJune** [sofastack/sofa-boot#819]

**Comment by khotyn** [comment]
可以在这里找到对应关系：https://www.sofastack.tech/projects/sofa-boot/overview/

**Comment by alaneuler** [comment]
代码角度的话，可以到 sofaboot-dependencies 这个模块下看其 maven 模块的 parent，3.6.0 中对应的是 Spring Boot 版本是 2.1.13.RELEASE
