### ISSUE TITLE
Prepare to release SOFABoot 3.7.0

### ISSUE THREAD

**Issue by HzjNeverStop** [sofastack/sofa-boot#831]

**Comment by longwusha** [comment]
There is a typo in 3.7.0 release change log.

'Provide English version REAME' means 'Provide English version README'?

**Comment by alaneuler** [comment]
> There is a typo in 3.7.0 release change log.
> 
> 'Provide English version REAME' means 'Provide English version README'?

yep, you are right!

It's now fixed~
