### ISSUE TITLE
SOFA 健康检查日志中加入当前检查进度

### ISSUE THREAD

**Issue by JohnnyCao** [sofastack/sofa-boot#837]
如，我要检测10项，那么可以类似如下反馈：
check item 1(DataSource): ok
check item 2(Mail): ......... -> 这里我就知道有问题了，可能网络问题卡主

**Comment by alaneuler** [comment]
Some enhancements:
1. before health check, printing all items
2. health check timeout for each item, defaulting to 60s

**Comment by seeflood** [comment]
任务可以 assign给 @it-linnan

**Comment by seeflood** [comment]
这个feature会assign给@it-linnan 哈
现在assign不了，好像得等@it-linnan 在这issue有留言才能assign~

**Comment by it-linnan** [comment]
🙌你好，我想认领这个任务

**Comment by seeflood** [comment]
> 🙌你好，我想认领这个任务

欢迎欢迎~已assign
