### ISSUE TITLE
国内现在有哪些公司在用sofa全家桶呢？

### ISSUE THREAD

**Issue by EzekR** [sofastack/sofa-boot#840]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
/area docs
> /area test-and-release

## Ask your question here
目前公司技术架构想转sofa，因为主要业务都是金融领域的。不知道国内有没有一些知名的大公司用了sofa全家桶的？

**Comment by nobodyiam** [comment]
There are some known users registered in [Awesome SOFA](https://www.sofastack.tech/awesome/)

**Comment by EzekR** [comment]
> There are some known users registered in [Awesome SOFA](https://www.sofastack.tech/awesome/)

thank you, sir
