### ISSUE TITLE
增加sofaTracer插件

### ISSUE THREAD

**Issue by kailll** [sofastack/sofa-boot#847]
sofa-tracer中新增了kafkamq，rabbitmq，rocketmq，springmessage，redis，mongodb插件，麻烦sofaboot增加下自动配置

**Comment by glmapper** [comment]
@kailll 可以直接使用 sofatracer 3.1.1. 版本提供的 starter

**Comment by glmapper** [comment]
@HzjNeverStop @alaneuler 现在 sofaBoot 除了 3.8.x 版本之外，还有那个版本在保持更新，我把 tracer starter 同步过来

**Comment by alaneuler** [comment]
> @HzjNeverStop @alaneuler 现在 sofaBoot 除了 3.8.x 版本之外，还有那个版本在保持更新，我把 tracer starter 同步过来

目前最新的是 3.8.x 系列，别的版本没有了。

**Comment by alaneuler** [comment]
新手任务描述：为 SOFATracer 中的 plugin：
1. kafkamq
2. rabbitmq
3. rocketmq
4. springmessage
5. redis
6. mongodb
增加 Spring Boot auto-configuration 配置。

**Comment by it-linnan** [comment]
🙋认领

**Comment by alaneuler** [comment]
@it-linnan 已 assign～

**Comment by it-linnan** [comment]
> @it-linnan 已 assign～

已提交PR [Add tracer autoconfigure. (#847) ](https://github.com/sofastack/sofa-boot/pull/875)
