### ISSUE TITLE
sofa健康检查不生效

### ISSUE THREAD

**Issue by helloxz** [sofastack/sofa-boot#853]
* sofa版本：`3.4.6`
* pom已启用`healthcheck-sofa-boot-starter`依赖
* java启动的时候添加了`-Dmanagement.port=xxx`参数

___
问题现象：
应用启动日志无报错，查看sofa日志目录下并没有health-check目录，`-Dmanagement.port=xxx`对应的端口没有监听，请问是哪里的原因？

**Comment by alaneuler** [comment]
@helloxz logs/sofa-runtime/common-error.log 里面有错误吗？
