### ISSUE TITLE
希望启动日志里/提供默认接口打印所有接口的URL路径列表集

### ISSUE THREAD

**Issue by keleqnma** [sofastack/sofa-boot#854]
## In what area(s)?

> /area runtime
/area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

接手前辈代码时一个个跟踪接口比较麻烦，又没有完善的文档，希望SOFABoot能提供该功能。
之前使用的Golang开发框架Gin就支持该功能，启动时会输出所有接口路径，METHOD类型，以及为该接口提供服务的方法。

**Comment by alaneuler** [comment]
你说的是 Spring MVC 里面的各个 Controller 吗？

**Comment by keleqnma** [comment]
> 你说的是 Spring MVC 里面的各个 Controller 吗？

是的

**Comment by seeflood** [comment]
@alaneuler Any idea about this issue? Can we make it a new community task?

**Comment by alaneuler** [comment]
@seeflood 这个会牵涉到部分内部代码逻辑，需要我们自己看下

**Comment by alaneuler** [comment]
@seeflood @keleqnma 这个能力 Spring Boot 本身已经提供了，https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html，见 mappings
