### ISSUE TITLE
add configuration for local env

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-boot#861]
Take over the auto detecting:
![image](https://user-images.githubusercontent.com/8054939/130422471-1c69d0eb-de1c-407b-a03b-30884478b2dc.png)

**Comment by seeflood** [comment]
我补充下任务描述：
## 背景
现在boot启动后会判断是怎么启动的、是不是通过IDE启动的（比如点idea上的运行按钮启动项目），如果是通过IDE启动的，会有些特殊功能（比如日志增强等）
但是代码里只判断了有没有idea的class，没判断别的IDE
## 需要做的优化
在LocalEnvUtil工具类里加一些判断：
- 也判断下是不是Eclipse启动的（判断下有没有加载Eclipse的class）
- 加个配置项，如果配了就认为是通过IDE启动的

## 这个功能的价值
简化本地开发

**Comment by aaronlinv** [comment]
🙋认领

**Comment by seeflood** [comment]
> 🙋认领

Cool !
有疑惑和问题欢迎发出来哈我们帮你讲

**Comment by Darian1996** [comment]
1. 配置项的优先级跟 class.forName 优先应该哪个优先
2. Eclipse 判断哪个主类
3. 任务可以重复认领吗？

**Comment by seeflood** [comment]
> 1. 配置项的优先级跟 class.forName 优先应该哪个优先
> 2. Eclipse 判断哪个主类
> 3. 任务可以重复认领吗？

@Darian1996 感谢反馈~
1. 配置项的优先级最高
2. 这个我也不知道诶，需要做任务的同学调研一下
3. 之前没考虑过这个问题，可以商量。我个人的想法是不能同时两个人领一个任务（避免开源变的太卷，哈哈） 但是如果一个已经分配出去的任务长时间没响应，那么其他人也可以重新认领~

你看下有其他感兴趣的任务不，比如：
Layotto的任务列表在https://github.com/mosn/layotto/issues/108  没打勾的都是没分配出去的任务；
SOFA-Boot之前的一个任务https://github.com/sofastack/sofa-boot/issues/851  领任务的同学最近在培训，特别忙没空做，如果你感兴趣的话可以协商下assign给你~

**Comment by Darian1996** [comment]
谢谢我先去看看 #851 ，梳理一下思路

**Comment by leemos-xx** [comment]
你好，这个任务似乎长时间没有跟进了，我是否可以认领来做？ @seeflood

**Comment by sususama** [comment]
@seeflood Hi，这个任务能够分配给我

**Comment by cccvip** [comment]
不确定这个任务是否还能做。 或许还有别的新手任务可以参与吗？

**Comment by HzjNeverStop** [comment]
该能力已经支持了，暂时先关闭该 issue
