### ISSUE TITLE
健康检查后置回调失败后，执行健康检查结果仍然为成功

### ISSUE THREAD

**Issue by hoodoly** [sofastack/sofa-boot#873]
## Describe the bug
1. 实现健康检查回调接口， 健康检查失败并返回异常。
![image](https://user-images.githubusercontent.com/15070948/131802604-6c54154d-e7fd-408a-bb46-12ed02b44c7b.png)

2. 执行健康检查，查看结果
![image](https://user-images.githubusercontent.com/15070948/131802035-e26cc0e2-6cd5-4637-97ae-be178cb72197.png)

sofaboot版本：3.8.0

**Comment by HzjNeverStop** [comment]
最新的版本已修复相关问题
