### ISSUE TITLE
sofaboot如何支持优雅关闭？

### ISSUE THREAD

**Issue by zeshaoy** [sofastack/sofa-boot#889]
您好  sofaboot在3.7.0版本开始基于spring boot 2.3.0构建，是不是同时也支持spring boot 2.3.0的优雅关闭新特性，配置方式是否和springboot一致？

**Comment by ujjboy** [comment]
@zeshaoy  这个逻辑跟 springboot 一致，没做特殊处理。 如果遇到问题，你在描述问题好了。

**Comment by zeshaoy** [comment]
> 
sofaboot执行graceful shutdown之后，会抛出sofa-boot-01-03001：failed to unregistere compenent，sofa-boot-01-01006，rpc-010010010：取消订阅元数据失败等问题，烦请帮忙确认

**Comment by HzjNeverStop** [comment]
已修复改问题
