### ISSUE TITLE
sofaboot执行graceful shutdown之后，会抛出sofa-boot-01-03001：failed to unregistere compenent

### ISSUE THREAD

**Issue by zeshaoy** [sofastack/sofa-boot#890]
在sofaboot 执行graceful shutdown之后，sofarpc逻辑并没有被正确执行，抛出了一系列sofa-boot-01-03001：failed to unregistere compenent问题。

**Comment by HzjNeverStop** [comment]
已知问题，已经在3.9.1版本修复：https://github.com/sofastack/sofa-boot/pull/880
