### ISSUE TITLE
考虑添加一个SofaBean注解

### ISSUE THREAD

**Issue by Kunple-w** [sofastack/sofa-boot#901]
## In what area(s)?

 /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Describe the feature

对应`@SofaService`和`@Service`/`@Component`的对应关系，是否应该有个`@SofaBean`对应Bean，以免去在配置类中重复写`@Bean`。

目前的写法
```java
public class MultiSofaServiceConfiguration {

    @Bean("multiSofaService")
    @SofaService
    SampleService service() {
        return new DefaultSampleService();
    }
}
```

**期望的写法:**
```java
public class MultiSofaServiceConfiguration {

    @SofaBean("multiSofaService")
    SampleService service() {
        return new DefaultSampleService();
    }
}
```

**Comment by MingJunDuan** [comment]
May refer to sofa-rpc issue [#1031](https://github.com/sofastack/sofa-rpc/issues/1031)

**Comment by HzjNeverStop** [comment]
已支持 @SofaServiceBean 注解，同时包含了 @SofaServic 和 @Component 的能力

**Comment by HzjNeverStop** [comment]
已支持 @SofaServiceBean 注解，同时包含了 @SofaServic 和 @ Component 的能力
