### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by akmalelias** [sofastack/sofa-boot#905]
## In what area(s)?

> /area docs

## Ask your question here

Most of the documentation (English version) is last updated in mid-2019.
Really appreciate it if the documentation can be updated to reflect the latest changes of the SOFABoot Framework.
Thank you so much for your great work.

**Comment by alaneuler** [comment]
We're upgrading Spring Boot version to 2.4.x in next SOFABoot release, and the document will also be updated then.
