### ISSUE TITLE
sofaboot从3.2.2切换到3.3.1版本导致抛出异常 No SofaRuntimeManager Found!

### ISSUE THREAD

**Issue by liu280790081** [sofastack/sofa-boot#915]
demo地址：[https://github.com/liu280790081/sofachannel-demo.git](https://github.com/liu280790081/sofachannel-demo.git)  分支为version-conflict
异常日志：[default.log](https://github.com/sofastack/sofa-boot/files/8129215/default.log)
![image](https://user-images.githubusercontent.com/12794525/155446440-68d9db36-9343-4a74-9236-72a0b5ff6221.png)

想知道版本切换后是否需要依赖其他包达到3.2.2的效果

**Comment by liu280790081** [comment]
看了下3.2.2与3.3.2的源码  发现了其中一个区别
3.2.2版本：
![image](https://user-images.githubusercontent.com/12794525/155452911-f02d1841-8e75-492f-99a3-545f8c65aa95.png)

3.3.2版本
![image](https://user-images.githubusercontent.com/12794525/155453226-954abbe1-ddc3-46cf-a7d4-404a03182f86.png)

其中3.3.2版本将SofaRuntimeManager 注入到了spring上下文中而在3.2.2版本中没有注入，这里是否引起了某些其他影响？

**Comment by alaneuler** [comment]
模块和基座同时升级了吗

**Comment by liu280790081** [comment]
> 模块和基座同时升级了吗

是的

**Comment by l10178** [comment]
在 provider的pom里 引入 runtime-sofa-boot-starter 试一下，也许能解决你的问题。
`
    <dependency>
      <groupId>com.alipay.sofa</groupId>
      <artifactId>runtime-sofa-boot-starter</artifactId>
      <version>${sofa.boot.version}</version>
    </dependency>
`
