### ISSUE TITLE
springboot2.2废弃了logging.path, 2.3已删除该属性，应使用logging.file.path

### ISSUE THREAD

**Issue by Kunple-w** [sofastack/sofa-boot#916]
## Describe the bug
Spring boot2.3已经不支持logging.path, sofa的各种包的log-conf.xml未更新

> You should be using logging.file.path with Spring Boot 2.2 and later. logging.path was deprecated in 2.2 in favour of logging.file.path. It was then removed in 2.3.

see https://github.com/spring-projects/spring-boot/issues/22295

## To Reproduce
1. 使用sofa3.10.0, 按照sofa guides配置`logging.path`,启动后并没有出现文档中的一些日志文件;
2. 降级为sample中的3.2.0版本，日志文件出现;

## Expected behavior
应支持`logging.file.path`属性

## Screenshots
**2个属性同时配置:**
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/15710694/155874767-ce54dd7b-65c8-46ba-965a-87ac592d22cf.png">
**log-con.xml**
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/15710694/155875097-d446bf67-e395-4456-ac96-18cc66573743.png">

## Environment:
- Project Version [e.g. SOFA-RPC 1.0.0] : sofaboot 3.9.0
- Language Version (e.g. Go 1.13): jdk8
- OS version (e.g. `uname -a`): Darwin
- IDE version: idea

**Comment by alaneuler** [comment]
下个版本修正

**Comment by l10178** [comment]
我所遇见的问题是，两个属性都配置，日志路径也没有生效，有遇到同样问题的吗。

**Comment by HzjNeverStop** [comment]
sofa 中间件中使用 sofa-common-tools 打印的日志，日志空间和 SOFABoot 应用程序是隔离的，因此可以同时使用 logging.path 以及 logging.file.path 属性分别定义 SOFA 中间件和 SOFABoot 应用程序的日志路径
