### ISSUE TITLE
BIZ 资源隔离问题

### ISSUE THREAD

**Issue by jhon-ye** [sofastack/sofa-boot#933]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
biz 合并部署的场景， 某一个biz 将 jvm 资源耗尽，此时宿主应用也会收到影响 目前如果处理这样的问题，

**Comment by ujjboy** [comment]
SOFABoot 本身不支持这种隔离，可以调研下 JDK 层面的，例如 [Dragonwell 的租户隔离](https://github.com/alibaba/dragonwell8/wiki/%E4%BD%BF%E7%94%A8Alibaba-Draognwell%E5%A4%9A%E7%A7%9F%E6%88%B7%E7%89%B9%E6%80%A7%E7%AE%A1%E6%8E%A7%E8%BF%90%E8%A1%8C%E6%97%B6%E8%B5%84%E6%BA%90) 看看

**Comment by coderDylan** [comment]
Tomcat Context和JDK Tenant做绑定
