### ISSUE TITLE
Provide a simplified version of result for readiness check

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-boot#947]
Result of `actuator/readiness` always contains full details of readiness check of all components. When application grows bigger, the result inflates quickly (bigger than 300K). Need for a simplified version is urgent to avoid useless network traffic and other weird problems, as infrastructures like K8S just need an HTTP status code of `readinessProbe` or `livenessProbe`.

**Comment by HzjNeverStop** [comment]
#957
