### ISSUE TITLE
源码解析：SOFABoot  HealthCheck 机制解析

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-boot#954]
SOFABoot 的健康检查机制为微服务应用发布提供了可靠的检查手段，SOFABoot 利用 Spring 启动期间的事件 listener 作为 hook，本任务需要说明 SOFABoot 如何做到可靠健康检查的。

**Comment by it-linnan** [comment]
[源码解析：SOFABoot HealthCheck 机制解析.md](https://github.com/sofastack/sofa-boot/files/8866099/SOFABoot.HealthCheck.md)

**Comment by it-linnan** [comment]
[SOFABoot.HealthCheck.md](https://github.com/sofastack/sofa-boot/files/8866575/SOFABoot.HealthCheck.md)
