### ISSUE TITLE
源码解析：SOFABoot 组件协议 binding 机制解析

### ISSUE THREAD

**Issue by alaneuler** [sofastack/sofa-boot#955]
SOFABoot 支持众多服务协议，例如 JVM 服务、Bolt 和 Dubbo 等，从 SOFA 组件、源码角度解析 SOFABoot 是如何实现的。

**Comment by it-linnan** [comment]
pr: [sofastack/sofastack.tech#977](https://github.com/sofastack/sofastack.tech/pull/977)
