### ISSUE TITLE
sofaboot 升级到 3.12.1，可否用 java 15 开发

### ISSUE THREAD

**Issue by lai53050960** [sofastack/sofa-boot#961]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here

sofaboot 升级到 3.12.1，springboot 适配到了 2.4.13，是不是意味着可以用java 15 开发了

**Comment by alaneuler** [comment]
JDK 11 是确认支持的，JAVA 15 我们这边没有验证过，理论上应该是 OK 的
