### ISSUE TITLE
dependency-check检查出的依赖漏洞如何进行修复？

### ISSUE THREAD

**Issue by StringKe** [sofastack/sofa-boot#965]
通过依赖检查检查，会有一些 `Blocker` 我如何修复它们？

最简单的办法是直接升级对应的版本，比如 `spring-boot-starter-web -> spring-boot-starter-json -> jackson-databind` 这样的依赖链，`spring-boot-starter-web` 的版本由 `sofaboot-dependencies -> sofa-boot-build` 决定的，也不是很好的升级版本怕引起 `sofastack` 中其他组件出现错误。

来自 阿里 codeup 提供的依赖检查
<img width="786" alt="CleanShot 2022-05-18 at 17 34 49@2x" src="https://user-images.githubusercontent.com/31089228/169008247-0a10cbd2-a029-4148-8cf3-3472aa84d3e6.png">

**Comment by ujjboy** [comment]
![image](https://user-images.githubusercontent.com/1424920/176857111-6f096f19-785c-4b67-8392-f19e65579f0d.png)

在自己的 `pom.xml`  里替换这个属性即可。 

`<jackson-bom.version>2.11.4</jackson-bom.version>`
