### ISSUE TITLE
如何实现模块的日志隔离

### ISSUE THREAD

**Issue by cxntsh** [sofastack/sofa-boot#988]
## In what area(s)?

> /area runtime
> /area operator
> /area placement
> /area docs
> /area test-and-release

## Ask your question here
基于SOFA-BOOT 的 ApplicationContext 或者 SOFA-ARK 的 Classloader 来进行模块化的拆分设计，如何实现日志的模块化隔离 ？，就是日志输出到不同的路径，同一模块的日志在一个目录下。

**Comment by Kunple-w** [comment]
关于日志，sofa有个[sofa-common-tools](https://github.com/sofastack/sofa-common-tools)，是不是你期望的用法

**Comment by alaneuler** [comment]
可以使用 sofa-common-tools 来做到你想要的日志模块化隔离。但是不建议这么做，这种隔离太细粒度了，感觉是应用本身应该拆分了。
